language: node_js
node_js:
  - "7"
install:
    - npm install
script:
- npm run prod
- npm run test
notifications:
slack: yamanotestudios:dG83TLAhuzOlxq1cx6ezLdnR
branches:
  only:
  - master
  - test-components
